#include <zephyr/dt-bindings/dt-util.h>
#ifndef ZMK_DT_BINDINGS_INPUT_PROCESSOR_KEYBIND_H
#define ZMK_DT_BINDINGS_INPUT_PROCESSOR_KEYBIND_H

#define DIRECTION_THRESHOLD 50

#endif /* ZMK_DT_BINDINGS_INPUT_PROCESSOR_KEYBIND_H */
